### ISSUE TITLE
Implementar ferramenta de login

### ISSUE THREAD

**Issue by tocktopus** [DudaElias/medalseats-frontend#2]
Essa issue consiste na implementação da ferramenta de login com os recursos necessários para a autenticação dos usuários. 
A ferramenta de login deve incluir:
- Campos para inserção do e-mail e senha do usuário
- Opção de recuperação de senha, caso o usuário esqueça suas credenciais
- Interface gráfica intuitiva
<br/>

**Protótipo da página de login:**

<img width="600" alt="Login" src="https://github.com/DudaElias/medalseats-frontend/assets/89416100/5b0058d0-4aba-4679-a223-ea66cfe46a68">
<br/>
<br/>

**Protótipo da página de recuperação de senha:**

<img width="600" alt="Esqueci a senha" src="https://github.com/DudaElias/medalseats-frontend/assets/89416100/2dd854c0-b5d3-4123-b359-242a0fd42f8b">

**Comment by gustavogitzel** [comment]
na segunda pagina, tem que colocar um botao para voltar para o login normal
