### ISSUE TITLE
Implementar formulário de cadastro

### ISSUE THREAD

**Issue by tocktopus** [DudaElias/medalseats-frontend#4]
Essa issue visa a implementação da página de cadastro dos usuários do sistema. Essa ferramenta deve conter:
- Campos para inserção de informações pessoais relevantes (ex.: nome, email, senha, data de nascimento)
- Verificação da entrada para garantir a validade dos dados fornecidos (o endereço de email deve válido, a senha deve ser segura, etc)
- Interface intuitiva e fácil de utilizar

<img width="560" alt="Captura de Tela 2024-04-19 às 10 17 56" src="https://github.com/DudaElias/medalseats-frontend/assets/42344174/c0e6e4c5-4aff-4dc7-97ad-e47cb04c801c">

**Comment by gustavogitzel** [comment]
criei o design do layout, vou implementar 🚀
